--- 
site: Inkpress
tagline: A small, lightweight, dead simple content management system built on free & open source technologies.
ga: UX-XXXXXX
twitter: brianmgonzalez
repo_url: git@github.com:briangonzalez/inkpress.git
authorized_users: 
  brian: b419dc186c1a9d5ea75aeefbfa6537a5
google_fonts_families:
  - Source+Code+Pro:400,700
  - Lato:300,400,700,900
  - PT+Sans:400,700,400italic,700italic
nav: 
  Home: " /home"
  Getting Started: " /getting-started"
  Documentation: " /documentation"
  About: " /about"
  Twitter: http://twitter.com/brianmgonzalez
  Github: http://github.com/briangonzalez/inkpress