--- 
site: Inkpress
tagline: A small, lightweight, dead simple content management system built on free & open source technologies.
ga: UA-38688465-1 
twitter: brianmgonzalez
repo_url: git@github.com:briangonzalez/inkpress.git
authorized_users: 
  brian: b419dc186c1a9d5ea75aeefbfa6537a5
google_fonts_families:
  - Lato:300,400,700,900
root_path: ' /home'
nav: 
  Home: " /home"
  Getting Started: " /getting-started"
  Documentation: " /documentation"
  About: " /about"
  Twitter: http://twitter.com/brianmgonzalez
  Github: http://github.com/briangonzalez/inkpress